server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    #content-type: text/html
    # 开发禁用缓存
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/ssmDb?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
    username: root
    password: 123456
    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
    # driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  data:
#     elasticsearch:
#      cluster-nodes: 127.0.0.1:9200
#      cluster-name: my-application
#      repositories:
#       enabled: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.domain
# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
logging:
  level:
    root: info
